# Generated by Django 4.1 on 2025-04-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_taxrates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Firma Adı/Ünvanı"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company_logos/",
                        verbose_name="Firma Logosu",
                    ),
                ),
                ("address", models.TextField(verbose_name="Firma Adresi")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Firma Telefonu"),
                ),
                ("web", models.URLField(verbose_name="Web Adresi")),
                ("email", models.EmailField(max_length=200, verbose_name="E-posta")),
                (
                    "tax_administration",
                    models.CharField(max_length=200, verbose_name="Vergi Dairesi"),
                ),
                (
                    "tax_id",
                    models.CharField(max_length=20, verbose_name="Vergi Kimlik No"),
                ),
                (
                    "kep_address",
                    models.EmailField(max_length=200, verbose_name="KEP Adresi"),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=200, verbose_name="Banka Adı"),
                ),
                ("iban_no", models.CharField(max_length=50, verbose_name="IBAN No")),
                (
                    "branch_code",
                    models.CharField(max_length=20, verbose_name="Şube Kodu"),
                ),
                (
                    "account_number",
                    models.CharField(max_length=20, verbose_name="Hesap No"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma Bilgisi",
                "verbose_name_plural": "Firma Bilgileri",
                "ordering": ["-created_at"],
            },
        ),
    ]
