# Generated by Django 4.1 on 2025-04-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_addresstype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addresstype",
            options={
                "ordering": ["name"],
                "verbose_name": "Adres Türü",
                "verbose_name_plural": "Adres Türleri",
            },
        ),
        migrations.AlterField(
            model_name="addresstype",
            name="name",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Adres Türü"
            ),
        ),
    ]
