# Generated by Django 4.1 on 2025-04-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_addresstype_options_alter_addresstype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="addresstype",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Açıklama"
            ),
        ),
        migrations.AddField(
            model_name="addresstype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
    ]
