# Generated by Django 4.1 on 2025-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_addresstype_description_addresstype_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Para Birimi Adı"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Kodu"),
                ),
                ("symbol", models.CharField(max_length=5, verbose_name="Sembol")),
            ],
        ),
        migrations.CreateModel(
            name="OfferStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Teklif Durumu"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Renk Kodu"
                    ),
                ),
            ],
        ),
    ]
