# Generated by Django 4.1 on 2025-05-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_currency_offerstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Departman Adı"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silindi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Departman",
                "verbose_name_plural": "Departmanlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Pozisyon Adı")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silindi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pozisyon",
                "verbose_name_plural": "Pozisyonlar",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={
                "ordering": ["name"],
                "verbose_name": "Para Birimi",
                "verbose_name_plural": "Para Birimleri",
            },
        ),
        migrations.AlterModelOptions(
            name="offerstatus",
            options={
                "ordering": ["name"],
                "verbose_name": "Teklif Durumu",
                "verbose_name_plural": "Teklif Durumları",
            },
        ),
    ]
