# Generated by Django 4.1 on 2025-05-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_department_position_alter_currency_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Banka Adı")),
            ],
            options={
                "verbose_name": "Banka",
                "verbose_name_plural": "Bankalar",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="position",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.department",
            ),
        ),
    ]
