# Generated by Django 4.1 on 2025-05-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_bank_address_bank_created_at_bank_eft_code_bank_fax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="bank_type",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Banka Tipi"
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="customer_service",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Müşteri Hizmetleri"
            ),
        ),
    ]
