# Generated by Django 4.1 on 2025-05-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_banktype_alter_bank_bank_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banktype",
            options={
                "ordering": ["name"],
                "verbose_name": "Banka Türü",
                "verbose_name_plural": "Banka Türleri",
            },
        ),
    ]
