# Generated by Django 4.1 on 2025-05-24 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_deliverytype_vehicletype_vehiclemodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehiclemodel",
            options={
                "ordering": ["brand", "name"],
                "verbose_name": "Araç Modeli",
                "verbose_name_plural": "Araç Modelleri",
            },
        ),
        migrations.CreateModel(
            name="VehicleBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Araç Markası")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.vehicletype",
                        verbose_name="Araç Tipi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Araç Markası",
                "verbose_name_plural": "Araç Markaları",
                "ordering": ["vehicle_type", "name"],
                "unique_together": {("vehicle_type", "name")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="vehiclemodel",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="brand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.vehiclebrand",
                verbose_name="Araç Markası",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="vehiclemodel",
            unique_together={("brand", "name")},
        ),
        migrations.RemoveField(
            model_name="vehiclemodel",
            name="vehicle_type",
        ),
    ]
