# Generated by Django 4.1 on 2025-05-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0019_alter_vehiclemodel_options_vehiclebrand_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nakliye Firması"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nakliye Firması",
                "verbose_name_plural": "Nakliye Firmaları",
                "ordering": ["name"],
            },
        ),
    ]
