# Generated by Django 4.1 on 2025-05-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_deliverycompany"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="email",
            field=models.EmailField(
                blank=True, max_length=200, null=True, verbose_name="E-posta"
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="bank_logos/",
                verbose_name="Banka Logosu",
            ),
        ),
    ]
