# Generated by Django 4.1 on 2025-05-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_bank_email_bank_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverytype",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Silindi"),
        ),
        migrations.AlterField(
            model_name="deliverytype",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="deliverytype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nakliye Türü Adı"),
        ),
    ]
