# Generated by Django 4.1 on 2025-05-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_deliverytype_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverycompany",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adres"),
        ),
        migrations.AddField(
            model_name="deliverycompany",
            name="customer_service",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Müşteri Hizmetleri"
            ),
        ),
        migrations.AddField(
            model_name="deliverycompany",
            name="email",
            field=models.EmailField(
                blank=True, max_length=200, null=True, verbose_name="E-posta"
            ),
        ),
        migrations.AddField(
            model_name="deliverycompany",
            name="fax",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Fax"
            ),
        ),
        migrations.AddField(
            model_name="deliverycompany",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Silindi"),
        ),
        migrations.AddField(
            model_name="deliverycompany",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="delivery_companies/",
                verbose_name="Nakliye Firması Logosu",
            ),
        ),
        migrations.AddField(
            model_name="deliverycompany",
            name="phone",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Telefon"
            ),
        ),
        migrations.AddField(
            model_name="deliverycompany",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Web Sitesi"),
        ),
        migrations.AlterField(
            model_name="deliverycompany",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
    ]
