# Generated by Django 4.1 on 2025-05-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0023_deliverycompany_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicletype",
            options={
                "ordering": ["name"],
                "verbose_name": "Araç Türü",
                "verbose_name_plural": "Araç Türleri",
            },
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Silindi"),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Araç Türü"),
        ),
    ]
