# Generated by Django 4.1 on 2025-05-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0025_vehiclebrand_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclemodel",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Silindi"),
        ),
    ]
