# Generated by Django 4.1 on 2024-02-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={"verbose_name": "Ürün", "verbose_name_plural": "Ürünler"},
        ),
        migrations.AlterField(
            model_name="stock",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Ürün ID"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Silindi"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.CharField(max_length=30, unique=True, verbose_name="Ürün Adı"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Miktar"),
        ),
    ]
