# Generated by Django 4.1 on 2024-02-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_stock_options_alter_stock_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="category",
            field=models.CharField(
                choices=[
                    ("Boyalı Profil", "Boyalı Profil"),
                    ("Siyah Profil", "Siyah Profil"),
                    ("Boru", "Boru"),
                    ("Boyalı Boru", "Boyalı Boru"),
                    ("Sac", "Sac"),
                ],
                max_length=20,
                null=True,
                verbose_name="Kategori",
            ),
        ),
    ]
