# Generated by Django 4.1 on 2024-02-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_stock_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Adet", "Adet"),
                    ("Paket", "Paket"),
                    ("Kilogram", "Kilogram"),
                    ("Metre", "Metre"),
                ],
                max_length=20,
                null=True,
                verbose_name="Birim",
            ),
        ),
    ]
