# Generated by Django 4.1 on 2024-02-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_stock_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="quantity_box",
            field=models.IntegerField(default=0, verbose_name="İç Toplam"),
        ),
    ]
