# Generated by Django 4.1 on 2025-04-15 13:20

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_stock_quantity_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=timezone.now, verbose_name="Oluşturulma Tarihi"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
    ]
