# Generated by Django 4.1 on 2025-04-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_stock_created_at_stock_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="serial_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Seri Numarası",
            ),
        ),
    ]
