# Generated by Django 4.1 on 2025-04-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_stock_serial_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="stock",
            name="color",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Renk"
            ),
        ),
    ]
