# Generated by Django 4.1 on 2025-04-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_stock_created_at_stock_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="quantity_box",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="İç Toplam"
            ),
        ),
    ]
