# Generated by Django 4.1 on 2025-04-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_stock_quantity_box"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="quantity_box",
        ),
    ]
