# Generated by Django 4.1 on 2025-04-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("inventory", "0012_category_unit_alter_stock_category_alter_stock_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.category",
                verbose_name="Kategori",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.unit",
                verbose_name="Birim",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
    ]
