# Generated by Django 4.1 on 2025-04-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_alter_stock_category_alter_stock_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="stock_images/",
                verbose_name="Ürün Resmi",
            ),
        ),
    ]
