# Generated by Django 4.1 on 2025-04-18 12:58

import django.core.validators
from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_stock_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Ürün için bir resim yükleyin",
                null=True,
                upload_to="stock_images/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    inventory.models.validate_file_size,
                ],
                verbose_name="Ürün Resmi",
            ),
        ),
    ]
