# Generated by Django 4.1 on 2025-05-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_stockcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockcard",
            name="packer",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Paketçi"
            ),
        ),
        migrations.AddField(
            model_name="stockcard",
            name="quality_control",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Kalite Kontrol"
            ),
        ),
        migrations.AddField(
            model_name="stockcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
