# Generated by Django 4.1 on 2025-05-19 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0016_subcategory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0017_stockcard_packer_stockcard_quality_control_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.subcategory",
                verbose_name="Alt Kategori",
            ),
        ),
        migrations.CreateModel(
            name="StockLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("read", "Okuma"),
                            ("create", "Ekleme"),
                            ("update", "Güncelleme"),
                            ("delete", "Silme"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.stock",
                        verbose_name="Ürün",
                    ),
                ),
                (
                    "stockcard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.stockcard",
                        verbose_name="Stok Kartı",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stok Logu",
                "verbose_name_plural": "Stok Logları",
                "ordering": ["-timestamp"],
            },
        ),
    ]
