# Generated by Django 4.1 on 2025-05-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0068_offer_description"),
        ("inventory", "0018_stock_subcategory_stocklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="barcode",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Barkod Numarası"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="brand",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Marka"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
        migrations.AddField(
            model_name="stock",
            name="expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Son Kullanma Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AddField(
            model_name="stock",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Raf/Konum"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="manufacturer",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Üretici"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="min_stock_level",
            field=models.IntegerField(default=0, verbose_name="Minimum Stok Seviyesi"),
        ),
        migrations.AddField(
            model_name="stock",
            name="model",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Model"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Alış Fiyatı",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Satış Fiyatı",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.supplier",
                verbose_name="Tedarikçi",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="warranty_period",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Garanti Süresi"
            ),
        ),
    ]
