# Generated by Django 4.1 on 2025-05-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_stock_barcode_stock_brand_stock_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockcard",
            name="barcode",
        ),
        migrations.AddField(
            model_name="stockcard",
            name="barcode_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Barkod Numarası",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Barkod Numarası",
            ),
        ),
    ]
