# Generated by Django 4.1 on 2024-02-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0005_stock_quantity_box"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Müşteri ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Müşteri Adı"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("address", models.CharField(max_length=220, verbose_name="Adres")),
                ("web", models.CharField(max_length=220, verbose_name="Web Adresi")),
                (
                    "representative",
                    models.CharField(max_length=220, verbose_name="Temsilci"),
                ),
                ("position", models.CharField(max_length=220, verbose_name="Görevi")),
                (
                    "mobile_phone",
                    models.CharField(max_length=20, verbose_name="Cep Telefonu"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-Mail"
                    ),
                ),
                (
                    "tax_id",
                    models.PositiveIntegerField(
                        max_length=12, verbose_name="Vergi Kimlik Numarası"
                    ),
                ),
                (
                    "tax_administration",
                    models.CharField(max_length=220, verbose_name="Vergi Dairesi"),
                ),
                (
                    "kep_address",
                    models.CharField(max_length=220, verbose_name="KEP Adresi"),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=220, verbose_name="Banka Adı"),
                ),
                (
                    "iban_no",
                    models.CharField(max_length=220, verbose_name="IBAN Numarası"),
                ),
                (
                    "branch_code",
                    models.PositiveIntegerField(
                        max_length=12, verbose_name="Şube Kodu"
                    ),
                ),
                (
                    "account_number",
                    models.PositiveIntegerField(
                        max_length=12, verbose_name="Hesap Numarası"
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silindi"),
                ),
            ],
            options={
                "verbose_name": "Müşteri",
                "verbose_name_plural": "Müşteriler",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Şehir ID"
                    ),
                ),
                (
                    "city_name",
                    models.CharField(max_length=120, verbose_name="Şehir Adı"),
                ),
            ],
            options={
                "verbose_name": "Şehir",
                "verbose_name_plural": "Şehirler",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Ülke ID"
                    ),
                ),
                (
                    "country_name",
                    models.CharField(max_length=120, verbose_name="Ülke Adı"),
                ),
            ],
            options={
                "verbose_name": "Ülke",
                "verbose_name_plural": "Ülkeler",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Pozisyon ID"
                    ),
                ),
                (
                    "department_name",
                    models.CharField(max_length=120, verbose_name="Pozisyon Adı"),
                ),
            ],
            options={
                "verbose_name": "Departman",
                "verbose_name_plural": "Departmanlar",
            },
        ),
        migrations.CreateModel(
            name="PurchaseBill",
            fields=[
                (
                    "billno",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Fatura No"
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True, verbose_name="Tarih")),
            ],
            options={
                "verbose_name": "Satınalma Faturası",
                "verbose_name_plural": "Satınalma Faturaları",
            },
        ),
        migrations.CreateModel(
            name="SaleBill",
            fields=[
                ("billno", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=12)),
                ("address", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("tax_id", models.CharField(max_length=10)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.buyer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Satış Faturası",
                "verbose_name_plural": "Satış Faturaları",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Tedarikçi ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Tedarikçi Adı"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="Telefon"
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Adres")),
                ("country", models.CharField(max_length=220, verbose_name="Ülke")),
                ("city", models.CharField(max_length=220, verbose_name="Şehir")),
                ("county", models.CharField(max_length=220, verbose_name="İlçe")),
                ("web", models.CharField(max_length=220, verbose_name="Web Adresi")),
                (
                    "representative",
                    models.CharField(max_length=220, verbose_name="Temsilci"),
                ),
                ("position", models.CharField(max_length=220, verbose_name="Görevi")),
                (
                    "mobile_phone",
                    models.CharField(max_length=20, verbose_name="Cep Telefonu"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-Mail"
                    ),
                ),
                (
                    "tax_id",
                    models.PositiveIntegerField(
                        max_length=12, verbose_name="Vergi Kimlik Numarası"
                    ),
                ),
                (
                    "tax_administration",
                    models.CharField(max_length=220, verbose_name="Vergi Dairesi"),
                ),
                (
                    "kep_address",
                    models.CharField(max_length=220, verbose_name="KEP Adresi"),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=220, verbose_name="Banka Adı"),
                ),
                (
                    "iban_no",
                    models.CharField(max_length=220, verbose_name="IBAN Numarası"),
                ),
                (
                    "branch_code",
                    models.PositiveIntegerField(
                        max_length=12, verbose_name="Şube Kodu"
                    ),
                ),
                (
                    "account_number",
                    models.PositiveIntegerField(
                        max_length=12, verbose_name="Hesap Numarası"
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silindi"),
                ),
            ],
            options={
                "verbose_name": "Tedarikçi",
                "verbose_name_plural": "Tedarikçiler",
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Miktar")),
                (
                    "perprice",
                    models.IntegerField(default=1, verbose_name="Birim Fiyat"),
                ),
                (
                    "totalprice",
                    models.IntegerField(default=1, verbose_name="Toplam Fiyat"),
                ),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salebillno",
                        to="transactions.salebill",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saleitem",
                        to="inventory.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Satılan Ürün",
                "verbose_name_plural": "Satılan Ürünler",
            },
        ),
        migrations.CreateModel(
            name="SaleBillDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eway",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Uzaklık"
                    ),
                ),
                (
                    "veh",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Araç"
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Satınalma Emri",
                    ),
                ),
                ("po", models.CharField(blank=True, max_length=50, null=True)),
                ("cgst", models.CharField(blank=True, max_length=50, null=True)),
                ("sgst", models.CharField(blank=True, max_length=50, null=True)),
                ("igst", models.CharField(blank=True, max_length=50, null=True)),
                ("cess", models.CharField(blank=True, max_length=50, null=True)),
                ("tcs", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "total",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Toplam"
                    ),
                ),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saledetailsbillno",
                        to="transactions.salebill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Satış Faturası Detayı",
                "verbose_name_plural": "Satış Faturası Detayları",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Makbuz ID"
                    ),
                ),
                ("created_date", models.DateField(verbose_name="Tarih")),
                (
                    "serial_number",
                    models.CharField(max_length=10, verbose_name="Seri No"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Nakit", "Nakit"),
                            ("Çek", "Çek"),
                            ("Senet", "Senet"),
                            ("Kredi Kartı", "Kredi Kartı"),
                        ],
                        max_length=120,
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                (
                    "payment_total",
                    models.IntegerField(max_length=120, verbose_name="Ödeme Toplamı"),
                ),
                (
                    "payment_one_payment_type",
                    models.CharField(
                        choices=[
                            ("Nakit", "Nakit"),
                            ("Çek", "Çek"),
                            ("Senet", "Senet"),
                            ("Kredi Kartı", "Kredi Kartı"),
                        ],
                        max_length=120,
                        verbose_name="Ödeme 1 Cinsi",
                    ),
                ),
                ("payment_one_date", models.DateField(verbose_name="Ödeme 1 Tarihi")),
                (
                    "payment_one_description",
                    models.CharField(max_length=220, verbose_name="Ödeme 1 Açıklama"),
                ),
                (
                    "payment_one_amount",
                    models.IntegerField(max_length=120, verbose_name="Ödeme 1 Tutarı"),
                ),
                (
                    "payment_two_payment_type",
                    models.CharField(
                        choices=[
                            ("Nakit", "Nakit"),
                            ("Çek", "Çek"),
                            ("Senet", "Senet"),
                            ("Kredi Kartı", "Kredi Kartı"),
                        ],
                        max_length=120,
                        verbose_name="Ödeme 2 Cinsi",
                    ),
                ),
                ("payment_two_date", models.DateField(verbose_name="Ödeme 2 Tarihi")),
                (
                    "payment_two_description",
                    models.CharField(max_length=220, verbose_name="Ödeme 2 Açıklama"),
                ),
                (
                    "payment_two_amount",
                    models.IntegerField(max_length=120, verbose_name="Ödeme 2 Tutarı"),
                ),
                (
                    "payment_three_payment_type",
                    models.CharField(
                        choices=[
                            ("Nakit", "Nakit"),
                            ("Çek", "Çek"),
                            ("Senet", "Senet"),
                            ("Kredi Kartı", "Kredi Kartı"),
                        ],
                        max_length=120,
                        verbose_name="Ödeme 3 Cinsi",
                    ),
                ),
                ("payment_three_date", models.DateField(verbose_name="Ödeme 3 Tarihi")),
                (
                    "payment_three_description",
                    models.CharField(max_length=220, verbose_name="Ödeme 3 Açıklama"),
                ),
                (
                    "payment_three_amount",
                    models.IntegerField(max_length=120, verbose_name="Ödeme 3 Tutarı"),
                ),
                (
                    "payment_handwrite",
                    models.CharField(max_length=220, verbose_name="Tutar Yazı İle"),
                ),
                (
                    "collector",
                    models.CharField(max_length=220, verbose_name="Tahsil Eden"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silindi"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.buyer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahsilat Makbuzu",
                "verbose_name_plural": "Tahsilat Makbuzları",
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Miktar")),
                (
                    "perprice",
                    models.IntegerField(default=1, verbose_name="Birim Fiyat"),
                ),
                (
                    "totalprice",
                    models.IntegerField(default=1, verbose_name="Toplam Fiyat"),
                ),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchasebillno",
                        to="transactions.purchasebill",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchaseitem",
                        to="inventory.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
            },
        ),
        migrations.CreateModel(
            name="PurchaseBillDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eway",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Uzaklık"
                    ),
                ),
                (
                    "veh",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Araç"
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Varış Yeri"
                    ),
                ),
                (
                    "po",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Satınalma Emri",
                    ),
                ),
                ("cgst", models.CharField(blank=True, max_length=50, null=True)),
                ("sgst", models.CharField(blank=True, max_length=50, null=True)),
                ("igst", models.CharField(blank=True, max_length=50, null=True)),
                ("cess", models.CharField(blank=True, max_length=50, null=True)),
                ("tcs", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "total",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Toplam"
                    ),
                ),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchasedetailsbillno",
                        to="transactions.purchasebill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Satınalma Fatura Detayı",
                "verbose_name_plural": "Satınalma Fatura Detayları",
            },
        ),
        migrations.AddField(
            model_name="purchasebill",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchasesupplier",
                to="transactions.supplier",
                verbose_name="Tedarikçi",
            ),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Pozisyon ID"
                    ),
                ),
                (
                    "position_name",
                    models.CharField(max_length=120, verbose_name="Pozisyon Adı"),
                ),
                (
                    "department_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pozisyon",
                "verbose_name_plural": "Pozisyonlar",
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Nakliye ID"
                    ),
                ),
                (
                    "courier_name",
                    models.CharField(max_length=120, verbose_name="Şoför Adı / Soyadı"),
                ),
                (
                    "courier_id",
                    models.IntegerField(
                        help_text="Sadece Numerik Karakterler",
                        max_length=11,
                        verbose_name="Şoför T.C. Kimlik No",
                    ),
                ),
                (
                    "courier_phone",
                    models.CharField(max_length=11, verbose_name="Şoför Telefonu"),
                ),
                (
                    "courier_vehicle",
                    models.CharField(
                        choices=[
                            ("Otomobil", "OTOMOBİL"),
                            ("Kamyonet", "KAMYONET"),
                            ("Pikap", "PİKAP"),
                            ("Kamyon", "KAMYON"),
                            ("Tır", "TIR"),
                        ],
                        max_length=220,
                        verbose_name="Şoför Aracı",
                    ),
                ),
                (
                    "vehicle_plate",
                    models.CharField(max_length=20, verbose_name="Şoför Plakası"),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silindi"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.buyer",
                    ),
                ),
                (
                    "sale_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.saleitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nakliye",
                "verbose_name_plural": "Nakliyeler",
            },
        ),
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="İlçe ID"
                    ),
                ),
                (
                    "county_name",
                    models.CharField(max_length=120, verbose_name="İlçe Adı"),
                ),
                (
                    "city_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.city",
                    ),
                ),
                (
                    "country_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "İlçe",
                "verbose_name_plural": "İlçeler",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="country_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.country",
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.city",
                verbose_name="Şehir",
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.country",
                verbose_name="Ülke",
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.county",
                verbose_name="İlçe",
            ),
        ),
    ]
