# Generated by Django 4.1 on 2024-02-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_name",
            field=models.CharField(max_length=120, verbose_name="Departman Adı"),
        ),
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Departman ID"
            ),
        ),
    ]
