# Generated by Django 4.1 on 2024-02-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_department_department_name_alter_department_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="position",
            old_name="department_name",
            new_name="department",
        ),
    ]
