# Generated by Django 4.1 on 2024-02-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_rename_department_name_position_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.department",
                verbose_name="Departmanı",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.position",
                verbose_name="Görevi",
            ),
        ),
    ]
