# Generated by Django 4.1 on 2024-02-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_buyer_department_alter_buyer_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="position",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.position",
                verbose_name="Görevi",
            ),
            preserve_default=False,
        ),
    ]
