# Generated by Django 4.1 on 2024-02-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_buyer_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="id",
            new_name="country_id",
        ),
        migrations.AlterField(
            model_name="buyer",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.position",
                verbose_name="Görevi",
            ),
        ),
    ]
