# Generated by Django 4.1 on 2024-02-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_rename_country_id_country_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="country_name",
            new_name="country",
        ),
    ]
