# Generated by Django 4.1 on 2024-02-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_rename_country_name_country_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="country",
            new_name="country_name",
        ),
    ]
