# Generated by Django 4.1 on 2024-02-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_rename_country_country_country_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="id",
            new_name="country_id",
        ),
    ]
