# Generated by Django 4.1 on 2024-02-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_rename_id_country_country_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="country_id",
            new_name="id",
        ),
    ]
