# Generated by Django 4.1 on 2024-02-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0011_rename_country_id_country_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.country",
                verbose_name="Ülke",
            ),
            preserve_default=False,
        ),
    ]
