# Generated by Django 4.1 on 2024-02-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0013_alter_buyer_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Banka ID"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=120, verbose_name="Banka Adı"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="delivery",
            name="courier_id",
            field=models.IntegerField(
                max_length=11, verbose_name="Şoför T.C. Kimlik No"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="bank_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.bank",
                verbose_name="Banka Adı",
            ),
        ),
    ]
