# Generated by Django 4.1 on 2024-02-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0014_bank_alter_delivery_courier_id_alter_buyer_bank_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bank",
            options={"verbose_name": "Banka", "verbose_name_plural": "Bankalar"},
        ),
        migrations.AlterField(
            model_name="buyer",
            name="account_number",
            field=models.CharField(max_length=50, verbose_name="Hesap Numarası"),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="branch_code",
            field=models.CharField(max_length=50, verbose_name="Şube Kodu"),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="phone",
            field=models.CharField(max_length=12, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="tax_id",
            field=models.CharField(max_length=50, verbose_name="Vergi Kimlik Numarası"),
        ),
    ]
