# Generated by Django 4.1 on 2024-02-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0015_alter_bank_options_alter_buyer_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="phone",
            field=models.CharField(max_length=50, verbose_name="Telefon"),
        ),
    ]
