# Generated by Django 4.1 on 2024-02-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0016_alter_buyer_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="country_name",
        ),
        migrations.AddField(
            model_name="country",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="country",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
