# Generated by Django 4.1 on 2024-02-28 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0017_remove_country_country_name_country_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="city_name",
        ),
        migrations.RemoveField(
            model_name="city",
            name="country_name",
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.country",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="city",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
