# Generated by Django 4.1 on 2024-02-28 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0018_remove_city_city_name_remove_city_country_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="county",
            old_name="county_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="county",
            name="city_name",
        ),
        migrations.RemoveField(
            model_name="county",
            name="country_name",
        ),
        migrations.AddField(
            model_name="county",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.city",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="county",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.country",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="county",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
