# Generated by Django 4.1 on 2024-03-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0019_rename_county_name_county_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="billno",
            field=models.CharField(default=1, max_length=120, verbose_name="Fiş No"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="buyer",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.city",
                verbose_name="Şehir Adı",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.country",
                verbose_name="Ülke Adı",
            ),
        ),
    ]
