# Generated by Django 4.1 on 2024-03-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0020_delivery_billno_alter_buyer_city_alter_buyer_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="description",
            field=models.CharField(default=1, max_length=300, verbose_name="Not"),
            preserve_default=False,
        ),
    ]
