# Generated by Django 4.1 on 2024-03-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0021_delivery_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="explanation",
            field=models.CharField(default=1, max_length=120, verbose_name="İzahat"),
            preserve_default=False,
        ),
    ]
