# Generated by Django 4.1 on 2024-03-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0022_delivery_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="tonage",
            field=models.BooleanField(
                default=False, verbose_name="Tonajdan Sorumluyuz"
            ),
        ),
    ]
