# Generated by Django 4.1 on 2024-03-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0023_delivery_tonage"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="analysed",
            field=models.BooleanField(default=False, verbose_name="Analizli S-420"),
        ),
    ]
