# Generated by Django 4.1 on 2024-03-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0024_delivery_analysed"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Mail Order ID"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        max_length=220, verbose_name="Müşteri Adı Soyadı / Firma Adı"
                    ),
                ),
                ("address", models.CharField(max_length=220, verbose_name="Adres")),
                (
                    "phone",
                    models.CharField(
                        max_length=20, verbose_name="Mobil / Sabit Telefon"
                    ),
                ),
                (
                    "card_number",
                    models.IntegerField(max_length=16, verbose_name="Kart No"),
                ),
                (
                    "expiry_month",
                    models.IntegerField(
                        max_length=10, verbose_name="Son Kullanma Tarihi (Ay)"
                    ),
                ),
                (
                    "expiry_year",
                    models.IntegerField(
                        max_length=10, verbose_name="Son Kullanma Tarihi (Yıl)"
                    ),
                ),
                (
                    "security_code",
                    models.IntegerField(max_length=10, verbose_name="Güvenlik Kodu"),
                ),
                (
                    "amount",
                    models.IntegerField(
                        max_length=50, verbose_name="Ödeme Tutarı (Rakamla)"
                    ),
                ),
                (
                    "amount_write",
                    models.CharField(
                        max_length=220, verbose_name="Ödeme Tutarı (Yazıyla)"
                    ),
                ),
                ("date", models.DateField()),
                ("owner", models.CharField(max_length=220, verbose_name="Kart Sahibi")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silindi"),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.bank",
                        verbose_name="Banka Adı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail Order",
                "verbose_name_plural": "Mail Orderlar",
            },
        ),
    ]
