# Generated by Django 4.1 on 2024-03-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0025_mailorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailorder",
            name="date",
            field=models.DateField(verbose_name="Ödeme Tarihi"),
        ),
    ]
