# Generated by Django 4.1 on 2024-03-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0026_alter_mailorder_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailorder",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Ödeme Tutarı (Rakamla)"
            ),
        ),
    ]
