# Generated by Django 4.1 on 2024-03-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0027_alter_mailorder_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryBill",
            fields=[
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bill",
                        serialize=False,
                        to="transactions.delivery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Malzeme Talep Fişi",
                "verbose_name_plural": "Malzeme Talep Fişleri",
            },
        ),
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "verbose_name": "Satış Faturası",
                "verbose_name_plural": "Satış Faturaları",
            },
        ),
        migrations.AlterField(
            model_name="receipt",
            name="payment_one_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Ödeme 1 Tutarı"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="payment_three_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Ödeme 3 Tutarı"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="payment_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Ödeme Toplamı"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="payment_two_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Ödeme 2 Tutarı"
            ),
        ),
    ]
