# Generated by Django 4.1 on 2024-03-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0034_deliverybill_billno_alter_deliverybill_delivery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverybill",
            name="billno",
        ),
        migrations.AlterField(
            model_name="deliverybill",
            name="delivery",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="bill",
                serialize=False,
                to="transactions.delivery",
            ),
        ),
    ]
