# Generated by Django 4.1 on 2024-03-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0035_remove_deliverybill_billno_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailOrderBill",
            fields=[
                (
                    "mailorder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bill",
                        serialize=False,
                        to="transactions.mailorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail Order",
                "verbose_name_plural": "Mail Orderlar",
            },
        ),
        migrations.CreateModel(
            name="ReceiptBill",
            fields=[
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bill",
                        serialize=False,
                        to="transactions.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahsilat Makbuzu",
                "verbose_name_plural": "Tahsilat Makbuzları",
            },
        ),
        migrations.AddField(
            model_name="receipt",
            name="description",
            field=models.CharField(default=1, max_length=220, verbose_name="Açıklama"),
            preserve_default=False,
        ),
    ]
