# Generated by Django 4.1 on 2024-03-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0036_mailorderbill_receiptbill_receipt_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="description",
        ),
    ]
