# Generated by Django 4.1 on 2024-03-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0037_remove_receipt_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebilldetails",
            name="eway",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="İrsaliye No"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="perprice",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Birim Fiyat"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="totalprice",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Toplam Fiyat"
            ),
        ),
    ]
