# Generated by Django 4.1 on 2024-03-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0038_alter_purchasebilldetails_eway_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="tax_rate",
            field=models.IntegerField(
                choices=[(0, "0%"), (8, "8%"), (10, "10%"), (20, "20%")],
                default=1,
                verbose_name="Vergi Oranı",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Toplam Tutar"
            ),
            preserve_default=False,
        ),
    ]
