# Generated by Django 4.1 on 2024-03-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0039_purchaseitem_tax_rate_purchaseitem_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Vergi Tutarı"
            ),
            preserve_default=False,
        ),
    ]
