# Generated by Django 4.1 on 2024-03-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0040_purchaseitem_tax_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseitem",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="total_with_tax",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                verbose_name="Vergiler Daihl Tutar",
            ),
            preserve_default=False,
        ),
    ]
