# Generated by Django 4.1 on 2024-03-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0041_remove_purchaseitem_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salebill",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.buyer",
                verbose_name="Müşteri",
            ),
        ),
    ]
