# Generated by Django 4.1 on 2024-03-22 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0042_alter_salebill_buyer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["-name"],
                "verbose_name": "Şehir",
                "verbose_name_plural": "Şehirler",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["-name"],
                "verbose_name": "Ülke",
                "verbose_name_plural": "Ülkeler",
            },
        ),
        migrations.AlterModelOptions(
            name="county",
            options={
                "ordering": ["-name"],
                "verbose_name": "İlçe",
                "verbose_name_plural": "İlçeler",
            },
        ),
        migrations.RenameField(
            model_name="purchasebilldetails",
            old_name="eway",
            new_name="waybill_no",
        ),
        migrations.RemoveField(
            model_name="purchasebilldetails",
            name="cess",
        ),
        migrations.RemoveField(
            model_name="purchasebilldetails",
            name="cgst",
        ),
        migrations.RemoveField(
            model_name="purchasebilldetails",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="purchasebilldetails",
            name="igst",
        ),
        migrations.RemoveField(
            model_name="purchasebilldetails",
            name="sgst",
        ),
        migrations.RemoveField(
            model_name="purchasebilldetails",
            name="tcs",
        ),
        migrations.RemoveField(
            model_name="purchasebilldetails",
            name="veh",
        ),
        migrations.AddField(
            model_name="purchasebilldetails",
            name="due_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Vade Tarihi"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchasebilldetails",
            name="waybill_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="İrsaliye Tarihi"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="tax_rate",
            field=models.IntegerField(
                choices=[(0, "0"), (8, "8"), (10, "10"), (20, "20")],
                verbose_name="Vergi Oranı",
            ),
        ),
    ]
