# Generated by Django 4.1 on 2024-03-22 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0043_alter_city_options_alter_country_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasebilldetails",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="purchasebilldetails",
            name="waybill_date",
        ),
        migrations.RemoveField(
            model_name="purchasebilldetails",
            name="waybill_no",
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="due_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Vade Tarihi"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="waybill_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="İrsaliye Tarihi"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="waybill_no",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="İrsaliye No"
            ),
        ),
    ]
