# Generated by Django 4.1 on 2024-04-03 13:08

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0044_remove_purchasebilldetails_due_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Şehir", "verbose_name_plural": "Şehirler"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Ülke", "verbose_name_plural": "Ülkeler"},
        ),
        migrations.AlterModelOptions(
            name="county",
            options={"verbose_name": "İlçe", "verbose_name_plural": "İlçeler"},
        ),
        migrations.AlterField(
            model_name="city",
            name="country",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="city",
                chained_model_field="city",
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.country",
            ),
        ),
    ]
