# Generated by Django 4.1 on 2024-04-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0046_alter_city_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bank",
            old_name="bank_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="department_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="position",
            old_name="position_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="bank",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
