# Generated by Django 4.1 on 2024-04-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0047_rename_bank_name_bank_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseitem",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Vade Tarihi"),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="tax_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Vergi Tutarı",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="tax_rate",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "0"), (8, "8"), (10, "10"), (20, "20")],
                null=True,
                verbose_name="Vergi Oranı",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="total_with_tax",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Vergiler Daihl Tutar",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="waybill_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="İrsaliye Tarihi"
            ),
        ),
    ]
