# Generated by Django 4.1 on 2024-04-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0049_saleitem_due_date_saleitem_tax_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salebilldetails",
            name="cess",
        ),
        migrations.RemoveField(
            model_name="salebilldetails",
            name="cgst",
        ),
        migrations.RemoveField(
            model_name="salebilldetails",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="salebilldetails",
            name="eway",
        ),
        migrations.RemoveField(
            model_name="salebilldetails",
            name="igst",
        ),
        migrations.RemoveField(
            model_name="salebilldetails",
            name="sgst",
        ),
        migrations.RemoveField(
            model_name="salebilldetails",
            name="tcs",
        ),
        migrations.RemoveField(
            model_name="salebilldetails",
            name="veh",
        ),
        migrations.AlterField(
            model_name="salebilldetails",
            name="po",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Satış Emri"
            ),
        ),
    ]
