# Generated by Django 4.1 on 2024-04-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0050_remove_salebilldetails_cess_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="perprice",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Birim Fiyat"
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="totalprice",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Toplam Fiyat"
            ),
        ),
    ]
