# Generated by Django 4.1 on 2024-04-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0051_alter_saleitem_perprice_alter_saleitem_totalprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.department",
                verbose_name="Departmanı",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="bank_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.bank",
                verbose_name="Banka Adı",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.city",
                verbose_name="Şehir Adı",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.country",
                verbose_name="Ülke Adı",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.county",
                verbose_name="İlçe",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.position",
                verbose_name="Görevi",
            ),
        ),
    ]
