# Generated by Django 4.1 on 2025-04-18 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0052_supplier_department_alter_supplier_bank_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="created_date",
        ),
        migrations.AddField(
            model_name="supplier",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
