# Generated by Django 4.1 on 2025-04-18 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0053_remove_supplier_created_date_supplier_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buyer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
