# Generated by Django 4.1 on 2025-04-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0055_remove_buyer_created_date_alter_buyer_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchasebilldetails",
            options={
                "verbose_name": "Satınalma Form Detayı",
                "verbose_name_plural": "Satınalma Form Detayları",
            },
        ),
        migrations.AddField(
            model_name="purchasebill",
            name="sequence",
            field=models.PositiveIntegerField(
                default=1, editable=False, verbose_name="Sıra No"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchasebill",
            name="year",
            field=models.PositiveIntegerField(
                default=1, editable=False, verbose_name="Yıl"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchasebill",
            name="billno",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Form No"
            ),
        ),
        migrations.AlterField(
            model_name="purchasebilldetails",
            name="po",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Satınalma Formu"
            ),
        ),
    ]
