# Generated by Django 4.1 on 2025-04-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0056_alter_purchasebilldetails_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salebill",
            options={
                "verbose_name": "Satış Formu",
                "verbose_name_plural": "Satış Formları",
            },
        ),
        migrations.RemoveField(
            model_name="salebill",
            name="address",
        ),
        migrations.RemoveField(
            model_name="salebill",
            name="email",
        ),
        migrations.RemoveField(
            model_name="salebill",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="salebill",
            name="tax_id",
        ),
        migrations.AddField(
            model_name="salebill",
            name="sequence",
            field=models.PositiveIntegerField(
                default=1, editable=False, verbose_name="Sıra No"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salebill",
            name="year",
            field=models.PositiveIntegerField(
                default=1, editable=False, verbose_name="Yıl"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="salebill",
            name="billno",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Form No"
            ),
        ),
        migrations.AlterField(
            model_name="salebill",
            name="buyer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salebuyer",
                to="transactions.buyer",
                verbose_name="Müşteri",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="salebill",
            name="time",
            field=models.DateTimeField(auto_now=True, verbose_name="Tarih"),
        ),
    ]
