# Generated by Django 4.1 on 2025-04-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_taxrates"),
        (
            "transactions",
            "0057_alter_salebill_options_remove_salebill_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseitem",
            options={
                "verbose_name": "Satın Alma Kalemi",
                "verbose_name_plural": "Satın Alma Kalemleri",
            },
        ),
        migrations.AlterModelOptions(
            name="saleitem",
            options={
                "verbose_name": "Satış Kalemi",
                "verbose_name_plural": "Satış Kalemleri",
            },
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="perprice",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Birim Fiyat"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.taxrates",
                verbose_name="Vergi Oranı",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="totalprice",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Toplam Fiyat"
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="perprice",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Birim Fiyat"
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.taxrates",
                verbose_name="Vergi Oranı",
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="totalprice",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Toplam Fiyat"
            ),
        ),
    ]
