# Generated by Django 4.1 on 2025-04-21 21:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_addresstype"),
        (
            "transactions",
            "0058_alter_purchaseitem_options_alter_saleitem_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="address_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.addresstype",
                verbose_name="Adres Tipi",
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="country_code",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=3,
                verbose_name="Ülke Kodu",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buyer",
            name="fax",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Fax"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Müşteri için bir logo yükleyin",
                null=True,
                upload_to="buyer_images/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    transactions.models.validate_file_size,
                ],
                verbose_name="Müşteri Logosu",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="address_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.addresstype",
                verbose_name="Adres Tipi",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="country_code",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=3,
                verbose_name="Ülke Kodu",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="fax",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Fax"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Tedarikçi için bir logo yükleyin",
                null=True,
                upload_to="supplier_images/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    transactions.models.validate_file_size,
                ],
                verbose_name="Tedarikçi Logosu",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="branch_code",
            field=models.CharField(max_length=12, verbose_name="Şube Kodu"),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="iban_no",
            field=models.CharField(max_length=26, verbose_name="IBAN Numarası"),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="phone",
            field=models.CharField(max_length=10, unique=True, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="tax_id",
            field=models.CharField(max_length=10, verbose_name="Vergi Kimlik Numarası"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="iban_no",
            field=models.CharField(max_length=26, verbose_name="IBAN Numarası"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(max_length=10, unique=True, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="tax_id",
            field=models.PositiveIntegerField(
                max_length=10, verbose_name="Vergi Kimlik Numarası"
            ),
        ),
    ]
