# Generated by Django 4.1 on 2025-05-05 19:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_currency_offerstatus"),
        ("inventory", "0015_alter_stock_image"),
        (
            "transactions",
            "0059_buyer_address_type_buyer_country_code_buyer_fax_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Teklif Numarası",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Tarih"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Geçerlilik Tarihi"
                    ),
                ),
                ("institution", models.CharField(max_length=200, verbose_name="Kurum")),
                ("unit", models.CharField(max_length=200, verbose_name="Birim")),
                (
                    "explanation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Teklif Açıklamaları"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.company",
                        verbose_name="Firma",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.currency",
                        verbose_name="Para Birimi",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.offerstatus",
                        verbose_name="Teklif Durumu",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.taxrates",
                        verbose_name="KDV Oranı",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfferBill",
            fields=[
                (
                    "offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bill",
                        serialize=False,
                        to="transactions.offer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teklif Formu",
                "verbose_name_plural": "Teklif Formları",
            },
        ),
        migrations.CreateModel(
            name="OfferItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_product_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Ürün Adı (Elle)",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Adet")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Birim Fiyat"
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="transactions.offer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.stock",
                        verbose_name="Ürün (Stoktan Seç)",
                    ),
                ),
            ],
        ),
    ]
