# Generated by Django 4.1 on 2025-05-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_department_position_alter_currency_options_and_more"),
        ("transactions", "0060_offer_offerbill_offeritem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={
                "ordering": ["-number"],
                "verbose_name": "Teklif",
                "verbose_name_plural": "Teklifler",
            },
        ),
        migrations.AlterModelOptions(
            name="offerbill",
            options={
                "verbose_name": "Teklif Formu Kalemi",
                "verbose_name_plural": "Teklif Formu Kalemleri",
            },
        ),
        migrations.AddField(
            model_name="offer",
            name="attention",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="İlgili Kişi"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.department",
                verbose_name="Departman",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.unit",
                verbose_name="Birim",
            ),
        ),
    ]
