# Generated by Django 4.1 on 2025-05-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_bank_position_department"),
        ("transactions", "0061_alter_offer_options_alter_offerbill_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="department",
        ),
        migrations.AlterField(
            model_name="buyer",
            name="bank_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.bank",
                verbose_name="Banka Adı",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.department",
                verbose_name="Departmanı",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.position",
                verbose_name="Görevi",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.bank",
                verbose_name="Banka Adı",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.department",
                verbose_name="Departman",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="bank_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.bank",
                verbose_name="Banka Adı",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.department",
                verbose_name="Departmanı",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.position",
                verbose_name="Görevi",
            ),
        ),
        migrations.DeleteModel(
            name="Bank",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Position",
        ),
    ]
