# Generated by Django 4.1 on 2025-05-05 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0062_remove_position_department_alter_buyer_bank_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Banka Adı")),
            ],
            options={
                "verbose_name": "Banka",
                "verbose_name_plural": "Bankalar",
            },
        ),
        migrations.AlterField(
            model_name="buyer",
            name="bank_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.bank",
                verbose_name="Banka Adı",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.bank",
                verbose_name="Banka Adı",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="bank_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.bank",
                verbose_name="Banka Adı",
            ),
        ),
    ]
