# Generated by Django 4.1 on 2025-05-05 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_bank_address_bank_created_at_bank_eft_code_bank_fax_and_more"),
        (
            "transactions",
            "0063_bank_alter_buyer_bank_name_alter_mailorder_bank_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="bank_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.bank",
                verbose_name="Banka Adı",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.bank",
                verbose_name="Banka Adı",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="bank_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.bank",
                verbose_name="Banka Adı",
            ),
        ),
        migrations.DeleteModel(
            name="Bank",
        ),
    ]
