# Generated by Django 4.1 on 2025-05-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_bank_address_bank_created_at_bank_eft_code_bank_fax_and_more"),
        ("transactions", "0064_alter_buyer_bank_name_alter_mailorder_bank_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="explanation",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="tax_rate",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="unit",
        ),
        migrations.AddField(
            model_name="offeritem",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.currency",
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AddField(
            model_name="offeritem",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.taxrates",
                verbose_name="KDV Oranı",
            ),
        ),
        migrations.AddField(
            model_name="offeritem",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.unit",
                verbose_name="Birim",
            ),
        ),
        migrations.AlterField(
            model_name="offeritem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Miktar"),
        ),
    ]
