# Generated by Django 4.1 on 2025-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0067_alter_contract_advance_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="description",
            field=models.TextField(
                default="\n            TEKLİF AÇIKLAMALARI:\n            - Ürünlerimize %20.00 K.D.V. eklenmiştir.\n            - Fiyatlarımız TL bazında peşin ödeme esasına göre düzenlenmiştir.\n            - Teklifimizdeki ürünler 2 yıl garanti kapsamındadır.\n            - Son ödeme tarihini takip eden 1 hafta içerisinde ödenmeyen faturalar için günlük %3 vade farkı uygulanır.\n            - Siparişiniz, yazılı onayınızı takiben hemen işleme alınacaktır. Stokta olmayan ürünler 15 iş günü içerisinde iletilmektedir.\n            - Bu teklif ve ekinde sunulan tüm bilgiler, verildiği kurum için özel olarak hazırlanmış olup sadece teklif verilenin kullanımına özeldir. Teklifi veren ve alan dışındaki üçüncü kurum/şahıslara iletilemez.\n            ",
                verbose_name="Teklif Açıklamaları",
            ),
        ),
    ]
