# Generated by Django 4.1 on 2025-05-19 19:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0016_subcategory"),
        ("transactions", "0068_offer_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailorder",
            name="buyer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.buyer",
                verbose_name="Müşteri",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailorder",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.company",
                verbose_name="Firma",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Oluşturulma Tarihi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailorder",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AddField(
            model_name="mailorder",
            name="number",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="Mail Order No"
            ),
        ),
        migrations.AddField(
            model_name="mailorder",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="mailorder",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="address",
            field=models.CharField(
                blank=True, max_length=220, null=True, verbose_name="Adres"
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Ödeme Tutarı (Rakamla)",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="amount_write",
            field=models.CharField(
                blank=True,
                max_length=220,
                null=True,
                verbose_name="Ödeme Tutarı (Yazıyla)",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="card_number",
            field=models.IntegerField(
                max_length=16,
                validators=[
                    django.core.validators.MinValueValidator(1000000000000000),
                    django.core.validators.MaxValueValidator(9999999999999999),
                ],
                verbose_name="Kart No",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="customer_name",
            field=models.CharField(
                blank=True,
                max_length=220,
                null=True,
                verbose_name="Müşteri Adı Soyadı / Firma Adı",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Mail Order Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="expiry_month",
            field=models.IntegerField(
                max_length=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Son Kullanma Tarihi (Ay)",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="expiry_year",
            field=models.IntegerField(
                max_length=10,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Son Kullanma Tarihi (Yıl)",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="owner",
            field=models.CharField(
                blank=True, max_length=220, null=True, verbose_name="Kart Sahibi"
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Mobil / Sabit Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="security_code",
            field=models.IntegerField(
                max_length=10,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="Güvenlik Kodu",
            ),
        ),
    ]
