# Generated by Django 4.1 on 2025-05-19 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0069_mailorder_buyer_mailorder_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailorder",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="card_number",
            field=models.CharField(max_length=19, verbose_name="Kart No"),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="expiry_month",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Son Kullanma Tarihi (Ay)",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="expiry_year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Son Kullanma Tarihi (Yıl)",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="security_code",
            field=models.CharField(max_length=3, verbose_name="Güvenlik Kodu"),
        ),
    ]
