# Generated by Django 4.1 on 2025-05-19 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0070_remove_mailorder_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailorder",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mail_orders",
                to="transactions.buyer",
                verbose_name="Müşteri",
            ),
        ),
    ]
