# Generated by Django 4.1 on 2025-05-19 22:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0016_subcategory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0071_alter_mailorder_buyer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailorder",
            name="is_active",
        ),
        migrations.AddField(
            model_name="mailorder",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.currency",
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="address",
            field=models.TextField(default=1, verbose_name="Adres"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=1230,
                max_digits=10,
                verbose_name="Ödeme Tutarı",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="amount_write",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Ödeme Tutarı (Yazı İle)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="bank",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.bank",
                verbose_name="Banka",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.buyer",
                verbose_name="Müşteri",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="card_number",
            field=models.CharField(max_length=19, verbose_name="Kart Numarası"),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="customer_name",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Müşteri Adı"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Sipariş Tarihi"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="expiry_year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Son Kullanma Tarihi (Yıl)",
            ),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="number",
            field=models.CharField(max_length=50, verbose_name="Sipariş Numarası"),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="owner",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Kart Sahibi"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="phone",
            field=models.CharField(default=123, max_length=20, verbose_name="Telefon"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="security_code",
            field=models.CharField(max_length=4, verbose_name="Güvenlik Kodu"),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
            preserve_default=False,
        ),
    ]
