# Generated by Django 4.1 on 2025-05-20 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0017_paymentmethod"),
        ("transactions", "0072_remove_mailorder_is_active_mailorder_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="payment_handwrite",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_one_amount",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_one_date",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_one_description",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_one_payment_type",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_three_amount",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_three_date",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_three_description",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_three_payment_type",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_total",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_two_amount",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_two_date",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_two_description",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="payment_two_payment_type",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="serial_number",
        ),
        migrations.AddField(
            model_name="receipt",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.company",
                verbose_name="Firma",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="number",
            field=models.CharField(
                default=1, max_length=50, unique=True, verbose_name="Makbuz Numarası"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="date",
            field=models.DateField(verbose_name="Mail Order Tarihi"),
        ),
        migrations.AlterField(
            model_name="mailorder",
            name="number",
            field=models.CharField(max_length=50, verbose_name="Mail Order Numarası"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="payment_method",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.paymentmethod",
                verbose_name="Ödeme Yöntemi",
            ),
        ),
        migrations.CreateModel(
            name="ReceiptPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Tutar"
                    ),
                ),
                (
                    "payment_handwrite",
                    models.CharField(max_length=220, verbose_name="Tutar Yazı İle"),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=220, null=True, verbose_name="Açıklama"
                    ),
                ),
                (
                    "payment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.paymentmethod",
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="transactions.receipt",
                    ),
                ),
            ],
        ),
    ]
