# Generated by Django 4.1 on 2025-05-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0017_paymentmethod"),
        ("transactions", "0073_remove_receipt_payment_handwrite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="payment_handwrite",
            field=models.CharField(
                blank=True, max_length=220, null=True, verbose_name="Tutar Yazı ile"
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="payment_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Ödeme Toplamı"
            ),
        ),
        migrations.AddField(
            model_name="receiptpayment",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.currency",
                verbose_name="Para Birimi",
            ),
        ),
    ]
