# Generated by Django 4.1 on 2025-05-21 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0074_receipt_payment_handwrite_receipt_payment_total_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receiptbill",
            options={
                "verbose_name": "Tahsilat Ödemesi",
                "verbose_name_plural": "Tahsilat Ödemeleri",
            },
        ),
    ]
