# Generated by Django 4.1 on 2025-05-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0075_alter_receiptbill_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receiptpayment",
            name="payment_handwrite",
        ),
        migrations.RemoveField(
            model_name="receiptpayment",
            name="payment_type",
        ),
    ]
