# Generated by Django 4.1 on 2025-05-22 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0017_paymentmethod"),
        ("transactions", "0076_remove_receiptpayment_payment_handwrite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptpayment",
            name="payment_method",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.paymentmethod",
                verbose_name="Ödeme Yöntemi",
            ),
        ),
    ]
