# Generated by Django 4.1 on 2025-05-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0077_receiptpayment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="E-Mail",
            ),
        ),
    ]
