# Generated by Django 4.1 on 2025-05-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0078_alter_buyer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-Mail"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Müşteri Adı"),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="phone",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Telefon"
            ),
        ),
    ]
