# Generated by Django 4.1 on 2025-05-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0079_alter_buyer_email_alter_buyer_name_alter_buyer_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receiptbill",
            options={
                "verbose_name": "Tahsilat Formu",
                "verbose_name_plural": "Tahsilat Formları",
            },
        ),
        migrations.AlterModelOptions(
            name="receiptpayment",
            options={
                "verbose_name": "Tahsilat Ödemesi",
                "verbose_name_plural": "Tahsilat Ödemeleri",
            },
        ),
    ]
