# Generated by Django 4.1 on 2025-05-24 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_deliverycompany"),
        ("transactions", "0080_alter_receiptbill_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ["-year", "-sequence"],
                "verbose_name": "Nakliye",
                "verbose_name_plural": "Nakliyeler",
            },
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="courier_vehicle",
        ),
        migrations.AddField(
            model_name="delivery",
            name="actual_delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Gerçekleşen Teslimat Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="courier_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                verbose_name="Şoför/Kurye Numarası",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.deliverycompany",
                verbose_name="Nakliye Firması",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_number",
            field=models.CharField(
                default=1,
                max_length=120,
                unique=True,
                verbose_name="Nakliye Form Numarası",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.deliverytype",
                verbose_name="Nakliye Türü",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="estimated_delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tahmini Teslimat Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="sequence",
            field=models.PositiveIntegerField(
                default=1, editable=False, verbose_name="Sıra No"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="shipping_company",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Kargo Firması"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("BEKLEMEDE", "Beklemede"),
                    ("YOLDA", "Yolda"),
                    ("TESLİM_EDİLDİ", "Teslim Edildi"),
                    ("İPTAL", "İptal"),
                ],
                default="BEKLEMEDE",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Takip Numarası"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="vehicle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.vehicletype",
                verbose_name="Araç Türü",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="waybill_number",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="İrsaliye Numarası"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="year",
            field=models.PositiveIntegerField(
                default=1, editable=False, verbose_name="Yıl"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="delivery",
            name="courier_id",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="T.C. Kimlik No"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="courier_name",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Şoför/Kurye Adı"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="courier_phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="Telefon"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="vehicle_plate",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Araç Plakası"
            ),
        ),
    ]
