# Generated by Django 4.1 on 2025-05-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_deliverycompany"),
        ("transactions", "0081_alter_delivery_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="shipping_company",
        ),
        migrations.AlterField(
            model_name="delivery",
            name="vehicle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.vehicletype",
                verbose_name="Araç Türü",
            ),
        ),
    ]
