# Generated by Django 4.1 on 2025-05-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0082_remove_delivery_shipping_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="deliverer",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Teslim Eden"
            ),
        ),
    ]
