# Generated by Django 4.1 on 2025-05-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0083_delivery_deliverer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="analysed",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Analizli S-420"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="billno",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Fiş No"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="description",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Not"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="explanation",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="İzahat"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="tonage",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Tonajdan Sorumluyuz"
            ),
        ),
    ]
