# Generated by Django 4.1 on 2025-05-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0084_alter_delivery_analysed_alter_delivery_billno_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="custom_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Elle Girilen Satış Kalemi",
            ),
        ),
    ]
