# Generated by Django 4.1 on 2025-05-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0085_saleitem_custom_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="billno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salebillno",
                to="transactions.salebill",
            ),
        ),
    ]
