# Generated by Django 4.1 on 2025-05-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0086_alter_saleitem_billno"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="sending_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Gönderim Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("BEKLEMEDE", "Beklemede"),
                    ("YOLDA", "Yolda"),
                    ("TESLİM EDİLDİ", "Teslim Edildi"),
                    ("İPTAL", "İptal"),
                ],
                default="BEKLEMEDE",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
    ]
