# Generated by Django 4.1 on 2025-05-28 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_deliverycompany"),
        ("transactions", "0087_delivery_sending_date_alter_delivery_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="address",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Adres"
            ),
        ),
        migrations.AddField(
            model_name="deliverybill",
            name="company",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.company",
                verbose_name="Firma",
            ),
        ),
    ]
