# Generated by Django 4.1 on 2025-05-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0088_delivery_address_deliverybill_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="iban_no",
            field=models.CharField(max_length=30, verbose_name="IBAN Numarası"),
        ),
    ]
