# Generated by Django 4.1 on 2025-05-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0089_alter_buyer_iban_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="iban_no",
            field=models.CharField(max_length=31, verbose_name="IBAN Numarası"),
        ),
    ]
