# Generated by Django 4.1 on 2025-05-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0090_alter_buyer_iban_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="country_code",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Ülke Kodu"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="iban_no",
            field=models.CharField(max_length=32, verbose_name="IBAN Numarası"),
        ),
    ]
