# Generated by Django 4.1 on 2025-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0091_alter_buyer_country_code_alter_buyer_iban_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="iban_no",
            field=models.CharField(max_length=32, verbose_name="IBAN Numarası"),
        ),
    ]
