# Generated by Django 4.1 on 2025-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0092_alter_supplier_iban_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="country_code",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Ülke Kodu"
            ),
        ),
    ]
